version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
